name: update overlays
run-name: update overlays
on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  update-overlays:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run update script
        exec: nix run .#update-overlays
